Repository horizon-eda/horizon-pool, pull requests merged in 2021-04, with the labels that each got.

#204 add 0603 LED 3D model
  3d_models/opto/LED_0603_1608Metric.step
  packages/opto/led/0603/package.json
Labels: ready to merge

#200 Add narrow variant to PJ301M-12 package
  packages/connector/audio/PJ301M-12-narrow/package.json
Labels: bot: fail, ready to merge

#196 Add USB-C Receptacle for USB2.0
  entities/connector/usb/type-c-usb20.json
  packages/connector/usb/jae/DX07SO16JA1/package.json
  parts/connector/usb/jae/DX07S016JA1R1500.json
  symbols/connector/usb/type-c-usb20.json
  units/connector/usb/type-c-usb20.json
Labels: ready to merge

#191 add FT4232H Quad USB UART interface
  entities/ic/manufacturer/ftdi/parts/FT4232HL.json
  parts/ic/manufacturer/ftdi/parts/FT4232HL.json
  symbols/ic/manufacturer/ftdi/parts/FT4232HL.json
  units/ic/manufacturer/ftdi/parts/FT4232HL.json
Labels: ready to merge

#206 Add testpoint symbol and basic package
  entities/connector/test-point.json
  packages/connector/tp/1mm-copper/package.json
  parts/connector/tp/1mm-copper.json
  symbols/connector/test-point.json
  units/connectors/test-point.json
Labels: bot: fail, ready to merge

#201 Add ideal diode MAX40200
  entities/ic/switch/ideal-diode-en.json
  parts/ic/switch/maxim/MAX40200AUK+.json
  symbols/ic/switch/ideal-diode-en.json
  units/ic/switch/ideal-diode-en.json
Labels: bot: pass, ready to merge

#207 Add 2520 SMD crystal package and 32MHz crystal
  packages/passive/crystal/smd-2520/package.json
  parts/passive/crystal/multicomp-pro/MCSJK-7E-32.00-8-10-60-B-10.json
  parts/passive/crystal/multicomp-pro/MCSJK-7E-base.json
Labels: ready to merge

#205 Add Molex 73251-1150 SMA connector
  packages/manufacturer/molex/73251-1150-vias/package.json
  packages/manufacturer/molex/73251-1150-vias/padstacks/pad.json
  packages/manufacturer/molex/73251-1150-vias/padstacks/pad2.json
  packages/manufacturer/molex/73251-1150/package.json
  packages/manufacturer/molex/73251-1150/padstacks/pad.json
  packages/manufacturer/molex/73251-1150/padstacks/pad2.json
  parts/connector/coaxial/molex/73251-1150.json
Labels: bot: pass, ready to merge

#208 Add 4ch ESD protection symbol and TI ESDS3x4 TVS diodes
  entities/diode/tvs/4ch-esd-protection.json
  parts/diode/tvs/texas-instruments/esds304.json
  parts/diode/tvs/texas-instruments/esds314.json
  parts/diode/tvs/texas-instruments/esds3x4.json
  symbols/diode/tvs/4ch-esd-protection.json
  units/diode/tvs/4ch-esd-protection.json
Labels: ready to merge

#210 Add XR21V1410 USB UART
  entities/ic/interface/usb/maxlinear/xr21v1410il16-f.json
  parts/ic/interface/usb/maxlinear/xr21v1410il16-f.json
  symbols/ic/interface/usb/maxlinear/xr21v1410il16-f.json
  units/ic/interface/usb/maxlinear/xr21v1410il16-f.json
Labels: bot: pass

#190 add FT232RL USB UART interface
  entities/ic/manufacturer/ftdi/parts/FT232RL.json
  packages/ic/smd/so/tssop-28/package.json
  parts/ic/manufacturer/ftdi/parts/FT232RL.json
  symbols/ic/manufacturer/ftdi/parts/FT232RL.json
  units/ic/manufacturer/ftdi/parts/FT232RL.json
Labels: ready to merge

#203 Add Molex 105400101 USB Type-C connector
  entities/connector/usb/type-c-shield.json
  packages/connector/usb/molex/1054500101/package.json
  parts/connector/usb/krhro/type-c-31-m-30.json
  parts/connector/usb/molex/1054500101.json
  symbols/connector/usb/type-c-shield.json
  units/connector/usb/type-c-shield.json
Labels: ready to merge

#211 Touch up QFN-16 package
  packages/ic/qfn/qfn-16/package.json
Labels: bot: pass

#213 Added MCP1640 device
  entities/ic/regulator/microchip/mcp1640.json
  parts/ic/regulator/microchip/MCP1640-ICHY.json
  parts/ic/regulator/microchip/MCP1640B-ICHY.json
  parts/ic/regulator/microchip/MCP1640C-ICHY.json
  parts/ic/regulator/microchip/MCP1640D-ICHY.json
  symbols/ic/regulator/microchip/mcp1640.json
  units/ic/regulator/microchip/mcp1640.json
Labels: bot: pass, ready to merge

#214 Add RFM9x device
  entities/ic/transceiver/rf/RFM9x.json
  packages/manufacturer/hoperf/rfm9x/package.json
  parts/ic/transceiver/rf/RFM95W-868S2.json
  parts/ic/transceiver/rf/RFM95W-915S2.json
  parts/ic/transceiver/rf/RFM96W-433S2.json
  parts/ic/transceiver/rf/RFM96W-470S2.json
  parts/ic/transceiver/rf/RFM98W-169S2.json
  parts/ic/transceiver/rf/RFM98W-433S2.json
  parts/ic/transceiver/rf/RFM98W-470S2.json
  parts/ic/transceiver/rf/RFM9x.json
  symbols/ic/transceiver/rf/RFM9x.json
  units/ic/transceiver/rf/RFM9x.json
Labels: bot: pass, needs some work

#215 Add RT9193 LDO regulator
  entities/ic/regulator/richtek/RT9193.json
  parts/ic/regulator/richtek/RT9193-33GB.json
  parts/ic/regulator/richtek/RT9193-GB.json
  symbols/ic/regulator/richtek/RT9193.json
  units/ic/regulator/richtek/RT9193.json
Labels: bot: pass, needs some work

#212 Add ATmega16/32
  3d_models/ic/qfp/TQFP-44_10x10mm_P0.8mm.step
  entities/ic/mcu/microchip/ATmega16_32.json
  packages/ic/smd/qfp/tqfp-44/package.json
  parts/ic/mcu/microchip/ATmega16A-AU.json
  parts/ic/mcu/microchip/ATmega16_32-TQFP.json
  parts/ic/mcu/microchip/ATmega32A-TQFP.json
  symbols/ic/mcu/microchip/ATmega16_32.json
  units/ic/mcu/microchip/ATmega16_32.json
Labels: bot: pass, ready to merge

#216 Fix a few small things in existing QFPs
  packages/ic/smd/qfp/LQFP64/package.json
  packages/ic/smd/qfp/TQFP44/package.json
  packages/manufacturer/intel/EQFP144/package.json
  packages/manufacturer/intel/EQFP144/padstacks/pad.json
  packages/manufacturer/microchip/TQFP176/package.json
Labels: bot: pass

#209 Add AZ1117{CD,IH} versions and DPAK TO-252-3 package
  entities/ic/regulator/three-terminal-adj.json
  packages/ic/smd/to/to-252-3/package.json
  packages/ic/smd/to/to-252-3/padstacks/pad.json
  parts/ic/regulator/diodes/AZ1117CD-1.2.json
  parts/ic/regulator/diodes/AZ1117CD-1.5.json
  parts/ic/regulator/diodes/AZ1117CD-1.8.json
  parts/ic/regulator/diodes/AZ1117CD-2.5.json
  parts/ic/regulator/diodes/AZ1117CD-3.3.json
  parts/ic/regulator/diodes/AZ1117CD-5.0.json
  parts/ic/regulator/diodes/AZ1117CD-ADJ.json
  parts/ic/regulator/diodes/AZ1117CD.json
  parts/ic/regulator/diodes/AZ1117IH-1.2.json
  parts/ic/regulator/diodes/AZ1117IH-1.5.json
  parts/ic/regulator/diodes/AZ1117IH-1.8.json
  parts/ic/regulator/diodes/AZ1117IH-2.5.json
  parts/ic/regulator/diodes/AZ1117IH-3.3.json
  parts/ic/regulator/diodes/AZ1117IH-5.0.json
  parts/ic/regulator/diodes/AZ1117IH-ADJ.json
  parts/ic/regulator/diodes/AZ1117IH.json
  symbols/ic/regulator/three-terminal-adj.json
  units/ic/regulators/three-terminal-adj.json
Labels: bot: warn, ready to merge

#177 add BT134W-600W Triac
  entities/transistor/triac.json
  parts/transistor/BT134W-600E.json
  symbols/transistor/triac.json
  units/transistor/triac.json
Labels: bot: pass, ready to merge

#218 Add TPS56339 buck converter
  entities/ic/regulator/buck-with-enable-and-boot.json
  parts/ic/regulator/ti/TPS56339DDC.json
  symbols/ic/regulator/three-terminal-with-enable-and-boot.json
  units/ic/regulator/boost-with-enable-and-boot.json
Labels: bot: pass

#220 Box 4ch ESD protection symbol
  symbols/diode/tvs/4ch-esd-protection.json
Labels: bot: pass

#192 add 93LC46B EEPROM
  entities/ic/memory/serial-flash.json
  parts/ic/manufacturer/microchip/93LC46BSN.json
  parts/ic/manufacturer/microchip/93xx46ABSN.json
  parts/ic/manufacturer/microchip/93xxx6ABSN.json
  symbols/ic/memory/serial-flash.json
  units/ic/memory/serial-flash.json
Labels: bot: pass, ready to merge

#159 Add MCU STM32F030CCT
  entities/ic/mcu/stm/STM32F030CC.json
  packages/ic/smd/qfp/QFP48/package.json
  parts/ic/mcu/stm/STM32F030CCT6.json
  symbols/ic/mcu/stm/STM32F030CC.json
  units/ic/mcu/stm/STM32F030CC.json
Labels: bot: pass, ready to merge

#219 Add molex picoblade 4-pin connector
  entities/connector/generic/004-mount.json
  packages/connector/header/molex/picoblade/53261-4pin/package.json
  parts/connector/header/molex/picoblade/53261-7004.json
  symbols/connector/generic/004-1-mount.json
  symbols/connector/generic/004-2-mount.json
  units/connector/generic/004-mount.json
Labels: bot: pass

#221 Polishing Opto-Triac with Zero-Cross-Detection
  symbols/opto/opto-isolator/opto-triac-zcd.json
Labels: bot: pass, ready to merge

#161 Add Digital Isolator Si8422xB
  entities/ic/isolator/digital_1_1.json
  parts/ic/isolator/silabs/Si8422AB-D-IS.json
  parts/ic/isolator/silabs/Si8422BB-D-IS.json
  parts/ic/isolator/silabs/Si8422xB-D-IS.json
  symbols/ic/isolator/digital_1_1.json
  units/ic/isolator/digital_1_1.json
Labels: bot: pass, ready to merge

#222 Add FTSH-107-xx-x-DV parts
  packages/connector/header/pin/ftsh/FTSH-107-xx-x-DV-xxx-A/package.json
  packages/connector/header/pin/ftsh/FTSH-107-xx-x-dv-xxx/package.json
  parts/connector/header/samtec/FTSH-107-01-L-DV-K-A.json
  parts/connector/header/samtec/FTSH-107-01-L-DV-K.json
  parts/connector/header/samtec/FTSH-107-xx-x-DV-x-A.json
  parts/connector/header/samtec/FTSH-107-xx-x-DV.json
Labels: bot: pass
