Repository horizon-eda/horizon-pool, pull requests merged in 2021-08, with the labels that each got.

#237 Fix SOT-363 assembly outline layer
  packages/ic/smd/sot/sot-363/package.json
Labels: bot: pass

#45 Added Dual Diode (series), SOT-23 package and BAV199
  3d_models/ic/so/SOT-23.step
  entities/diode/dual_diode_common_cathode.json
  entities/diode/dual_diode_series.json
  packages/ic/smd/sot/sot-23-alternate-silkscreen/package.json
  packages/ic/smd/sot/sot-23/package.json
  parts/diode/BAV170.json
  parts/diode/BAV199.json
  symbols/diodes/dual_diode_common_cathode.json
  symbols/diodes/dual_diode_series.json
  units/diodes/dual_diode_common_cathode.json
  units/diodes/dual_diode_series.json
Labels: ready to merge, bot: warn

#238 add SOIC-14 3D model
  3d_models/ic/so/SOIC-14_3.9x8.7mm_P1.27mm.step
  packages/ic/smd/soic/so-14/package.json
Labels: bot: fail
