Repository horizon-eda/horizon-pool, pull requests merged in 2021-12, with the labels that each got.

#248 MOC3063: Fix swapped A1/A2 pins
  parts/opto/opto-isolator/MOC3063SM.json
Labels: bot: pass

#77 Circular test pads
  entities/connector/test_point.json
  packages/connector/tp/1mm-copper/package.json
  packages/test_points/test_pad_0.5mm_diameter/package.json
  packages/test_points/test_pad_0.635mm_diameter/package.json
  packages/test_points/test_pad_1.27mm_diameter/package.json
  packages/test_points/test_pad_1.5mm_diameter/package.json
  packages/test_points/test_pad_1mm_diameter/package.json
  packages/test_points/test_pad_2.54mm_diameter/package.json
  packages/test_points/test_pad_2mm_diameter/package.json
  parts/connector/generic/test_pad.json
  symbols/connector/generic/test_point_diamond_large.json
  symbols/connector/generic/test_point_diamond_small.json
  symbols/connector/generic/test_point_large_circle.json
  symbols/connector/generic/test_point_large_circle_filled.json
  symbols/connector/generic/test_point_small_circle.json
  symbols/connector/generic/test_point_small_circle_filled.json
  units/connector/generic/test_point.json
Labels: bot: warn

#151 Add modular jack TE Connectivity 5555980-1
  3d_models/connector/modular/te/5555980-1.step
  packages/connector/modular/te/5555980-1/package.json
  parts/connector/modular/te/5555980-1.json
Labels: ready to merge, bot: pass

#255 Add Single Buffer SN74AHCT1G125 for Level Shifting
  entities/ic/buffer/1ch-buffer-with-en.json
  parts/ic/driver/ti/SN74AHCT1G125.json
  symbols/ic/buffer/1ch-buffer-with-en.json
  units/ic/buffer/1ch-buffer-with-en.json
Labels: bot: pass

#240 Add Analog Devices AD7764 24Bit ADC
  entities/ic/adc/analog-devices/AD7764.json
  parts/ic/adc/analog-devices/AD7764BRUZ.json
  symbols/ic/adc/analog-devices/AD7764.json
  units/ic/manufacturer/analog-devices/AD7764.json
Labels: bot: pass

#253 Add AMS1117 parts
  parts/ic/regulator/ams/AMS1117-1.5.json
  parts/ic/regulator/ams/AMS1117-1.8.json
  parts/ic/regulator/ams/AMS1117-2.5.json
  parts/ic/regulator/ams/AMS1117-2.85.json
  parts/ic/regulator/ams/AMS1117-3.3.json
  parts/ic/regulator/ams/AMS1117-5.0.json
  parts/ic/regulator/ams/AMS1117.json
Labels: bot: pass

#254 Add ST LDL1117 parts
  parts/ic/regulator/stm/LDL1117.json
  parts/ic/regulator/stm/LDL1117S12R.json
  parts/ic/regulator/stm/LDL1117S15R.json
  parts/ic/regulator/stm/LDL1117S18R.json
  parts/ic/regulator/stm/LDL1117S25R.json
  parts/ic/regulator/stm/LDL1117S30R.json
  parts/ic/regulator/stm/LDL1117S33R.json
  parts/ic/regulator/stm/LDL1117S50R.json
Labels: bot: pass

#246 Add part 34AA02T-I/OT
  entities/ic/memory/eeprom-i2c-2addr.json
  parts/ic/manufacturer/microchip/34AA02T-I_OT.json
  symbols/ic/memory/eeprom-i2c-2addr.json
  units/ic/memory/eeprom-i2c-2addr.json
Labels: bot: pass

#247 Add part S-1313D33-M5T1U3
  parts/ic/regulator/ablic/S-1313D33-M5T1U3.json
Labels: bot: pass

#251 Add STM32L15xCxTx
  entities/ic/mcu/stm/STM32L15xCxTx.json
  parts/ic/mcu/stm/STM32L151C8T6.json
  parts/ic/mcu/stm/STM32L15xCxTx.json
  symbols/ic/mcu/stm/STM32L15xCxTx.json
  units/ic/mcu/stm/STM32L15xCxTx.json
Labels: bot: pass

#259 Add OSHW silkscreen decals
  decals/oshw-no-text-silk.json
  decals/oshw-silk.json
Labels: bot: pass
