Repository horizon-eda/horizon-pool, pull requests merged in 2022-02, with the labels that each got.

#268 Add Keystone 4628 Fuse Holder
  entities/passive/fuse/fuse.json
  packages/fuse_holder/keystone/4628/package.json
  parts/fuse_holder/keystone/4628.json
  symbols/passive/fuse/fuse.json
  units/passive/fuse/fuse.json
Labels: bot: warn

#260 Add Horizon logo silkscreen decal
  decals/horizon-silk.json
Labels: bot: pass

#284 Add AO3401A MOSFET
  parts/transistor/pmos/AO3401A.json
Labels: bot: pass

#273 Add AP0901C Battery Protection
  entities/ic/battery_protection/diodes/AP9101C.json
  parts/ic/battery_protection/diodes/AP9101CAK6-ANTRG1.json
  symbols/ic/battery_protection/diodes/AP9101C.json
  units/ic/battery_protection/diodes/AP9101C.json
Labels: bot: pass

#274 Add DMG6968UDM Dual N-Channel MOSFET
  entities/transistor/dmg6968udm.json
  parts/transistor/nmos/DMG6968UDM-7.json
  symbols/transistor/dmg6968udm.json
  units/manufacturer/diodes/UDM6968DMG.json
Labels: needs some work, bot: pass
